{ repoRoot, inputs, pkgs, lib, system }:

lib.iogx.mkShell {
  name = "marlowe-docs-website";
  
  packages = [
    pkgs.prefetch-npm-deps
    pkgs.nodejs_18
    pkgs.nodejs_18.pkgs.npm
  ];

  scripts.gen-npm-deps-hash = {
    group = "marlowe-docs-website";
    description = "Run this whenever package-lock.json changes";
    exec = ''
      cd "$(git rev-parse --show-toplevel)"
      echo "# This file was generated by prefetch-npm-deps" > nix/gen/npm-deps-hash.nix
      echo "\"$(prefetch-npm-deps package-lock.json)\"" >> nix/gen/npm-deps-hash.nix
    '';
  };

  preCommit = {
    nixpkgs-fmt.enable = true;
  };
}
